### PR TITLE
frontend: use the react router Link element

### PR DESCRIPTION
**Pull request by vladikr**
This is a follow-up to #31 
It uses the reacts router Link element for internal redirections.

@machadovilaca

### CODE REVIEW

**Comment by vladikr** [comment]
@machadovilaca I've built an  :expr image  and started it here: http://logsviewer-xhdrwl.apps.cnv2.engineering.redhat.com

**Comment by machadovilaca** [comment]
For me, clicking the links already opened correctly.

The problem was directly opening for example http://logsviewer-xhdrwl.apps.cnv2.engineering.redhat.com/workloads/virtualmachineinstances?status=warning

I still think it has the issue.

**Comment by vladikr** [comment]
> For me, clicking the links already opened correctly.

I'm not sure why... 

I tried on several browsers and it didn't. 

openshift console also uses `Link` and `Route` from the react-router-dom
https://github.com/openshift/console/blob/master/frontend/public/components/monitoring/alerting.tsx

> 
> The problem was directly opening for example http://logsviewer-xhdrwl.apps.cnv2.engineering.redhat.com/workloads/virtualmachineinstances?status=warning
> 
> I still think it has the issue.

Yep, this doesn't solve routing.

**Comment by vladikr** [comment]
https://reactrouter.com/en/main/components/link

Intersting. Looks like Link makes the routing inside the client app and not by reloading the full document.

**Comment by vladikr** [comment]
> maybe changing:
> 
> ```
> mux.Handle("/", web)
> mux.HandleFunc("/healthz", app.healthz)
> mux.HandleFunc("/uploadLogs", app.uploadLogs)
> ...
> ```
> 
> to
> 
> ```
> mux.Handle("/*", web)
> mux.HandleFunc("/healthz", app.healthz)
> mux.HandleFunc("/uploadLogs", app.uploadLogs)
> ...
> ```
> 
> might work, gorilla/mux probably uses longest prefix match

We can do it, sure. But honestly think this is a reach issue, not our backend.

**Comment by vladikr** [comment]
Let's get this change in and then see how to deal with the whole routing issue.

**Pull request merged**
