### PR TITLE
Update dashboard with resource status counts and installed operators

### PR DESCRIPTION
**Pull request by machadovilaca**
newdash

### CODE REVIEW

**Comment by sradco** [comment]
@machadovilaca I dont this we need the lists of VMIs/pods/node. The first panel that shows the aggregations seems enough to me.
About the "Installed operators", where do we get this info from? Can we show more operators in the panel, not only one and with their version(The version can be as part of the operator name, not separate)?

**Comment by machadovilaca** [comment]
> @machadovilaca I dont think we need the lists of VMIs/pods/node. The first panel that shows the aggregations seems enough to me. About the "Installed operators", Can we show the full details in the panel instead of having them in the pop up ?

For now, I think we can leave the lists to fill some space, and maybe when we add more info to the dashboard we can remove those.

I think it would become too cluttered, we can later add a side tab with the list of operators and full details

**Comment by vladikr** [comment]
If we are going to present a list of any objects in the dashboard - I would only focus on problematic ones (failed) - but I think this is not necessary.

The inventory table is really awesome! 
It would be really great if we could allow clicking on the number of, say, failed VMs and it would bring you to the VMs list which is filtered only with the failed VMs

**Comment by machadovilaca** [comment]
but without it feels very empty
i think we can remove those later, when we add events/ must-gathers upload history, etc...

Screenshot from 2023-08-09 15-34-22

**Comment by vladikr** [comment]
> 

I don't mind. We can remove it later :)

**Comment by machadovilaca** [comment]
Now, clicks on the specific status in the inventory card, will redirect to the table with resources filtered by that status

**Comment by sradco** [comment]
> but without it feels very empty
> i think we can remove those later, when we add events/ must-gathers upload history, etc...
> 
> Screenshot from 2023-08-09 15-34-22
> 

I think that if you add the imported must-gather list and their creation date we don't need the other lists. I don't think it is a problem to have few panels. Especially if we plan to add additional panels like the events and insights rules. Alerts would also be very useful, but we need to see if it's possible to add to must-gather. I know that OCP planned to add that and I don't know if they did that eventually.

**Comment by vladikr** [comment]
I've tested it now. Seems that http://logsviewer-xxlwk6.apps.cnv2.engineering.redhat.com/workloads/migrations?status=unhealthy errors with 404.

**Comment by machadovilaca** [comment]
> I've tested it now. Seems that http://logsviewer-xxlwk6.apps.cnv2.engineering.redhat.com/workloads/migrations?status=unhealthy errors with 404.

@vladikr 

I think something similar happened to me once

I think the issue is that sometimes, on the UI URLs, it fetches from the backend, and not the UI

Maybe I would suggest prefixing backend endpoints with `/api`

**Comment by vladikr** [comment]
@machadovilaca I think this is a general issue.
For example: 
If you'll use this URL it will also resolve into 404:
`http://logsviewer-xxlwk6.apps.cnv2.engineering.redhat.com/workloads/virtualmachines`

but if you'll, go to `http://logsviewer-xxlwk6.apps.cnv2.engineering.redhat.com` then click workloads and choose Virtual Machines it will route correctly to the same URL, but this time it will work

**Comment by vladikr** [comment]
IIRC, there is some kind of route validation.

**Comment by vladikr** [comment]
@machadovilaca I think we need to return a function that uses the react-router-dom Route. Like in the `frontend/src/app/routes.tsx`

`<Route...`

**Pull request merged**
